{{- if .Values.dataVolume.pvc }}
# This IOC uses a data volume, so we will create a PVC for it
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.ioc_name }}-data
  labels:
    app: {{ .Values.ioc_name }}
    beamline: {{ .Values.beamline }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi
{{ else }}
# This IOC has no data volume, so we will mount the host filesystem
{{- end }}
