{{- define "ioc-instance.configmap" -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ .Values.ioc_name }}
  labels:
    app: {{ .Values.ioc_name }}
    beamline: {{ .Values.beamline }}
    ioc_version: {{ .Values.ioc_version | quote }}
    is_ioc: "True"
data:

{{- end -}}
