# IOCS can use a PVC as a data volume, or mount the host filesystem
{{- define "ioc-instance.volume" -}}

{{- if .Values.dataVolume.pvc }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.ioc_name }}-data
  labels:
    app: {{ .Values.ioc_name }}
    beamline: {{ .Values.beamline }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Mi

---
{{- end }}

{{- end }}

