# yaml-language-server: $schema=values.schema.json

# This file configures an ArgoCD app of apps that represent a
# group of beamline or accelerator IOCs and services. The configuration of the
# services are in the separate repo indicated by repoURL.

# This repository only controls which services and which versions of those
# services should be running on the cluster. It is recommended that this repo
# be updated by a CI/CD pipeline or configuration tools only.

# @schema description: "The ArgoCD project. At DLS this is the same as the beamline namespace. or 'accelerator'"
project: ""
destination:
  # @schema description: "The name of the destination cluster. e.g. 'i21' 'pollux' 'acastus'"
  name: ""
  # @schema description: "The namespace in the destination cluster. At DLS this is always the same as the project name"
  namespace: ""
source:
  # @schema description: "The URL of the Git repository containing the application manifests."
  repoURL: ""
  # @schema description: "The target revision (branch, tag, commit) of the Git repository."
  targetRevision: ""

# @schema type: [object, null]
# @schema mergeProperties: true
services:
  # Each item is of the form:
  #   service: service name as it appears in K8S (statefulset/deployment name).
  #     destination: optional override for destination parameters above.
  #       name: optional override for the deployment cluster above.
  #       namespace: optional override for namespace above.
  #     serviceChart: optional override for the helm chart to use. 
  #                 The path is always services/<serviceChart> within the repo.
  #     targetRevision: optional override for targetRevision above.
  #     repoURL: optional override for git repo to source the helm chart from
  #            the path is always services/<service> within that repo.
  #     valuesObject: An object that is passed as values to the helm chart.
  #                 This is merged with the default values.yaml in the repo,
  #                 with valuesObject taking precedence.
  #     valuesFiles: A list of paths to values.yaml files that are passed to
  #                 the helm chart. Subsequent files in the list override
  #                 the previous ones.
  #     removed: set to true to remove the service from the cluster.
  #     enabled: set to false to stop a service.

  # @schema type: [object, null]
  example1:

    # @schema type: [object, null]
    destination:

      # @schema type: string
      # @schema default: ""
      name: ""

      # @schema type: string
      # @schema default: ""
      namespace: ""

    # @schema type: object
    # @schema additionalProperties: {"type":"string","maxLength":63,"description":"Custom labels applied to the resource.","pattern":"^[a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]$|^[a-zA-Z0-9]$"}
    # @schema default: {}
    labels: {}

    # @schema type: string
    # @schema default: ""
    serviceChart: ""

    # @schema type: string
    # @schema default: ""
    targetRevision: ""

    # @schema type: string
    # @schema default: ""
    repoURL: ""

    # @schema type: boolean
    # @schema default: false
    removed: false

    # @schema type: boolean
    # @schema default: true
    enabled: true

    # @schema type: object
    # @schema default: {}
    valuesObject: {}

    # @schema type: array
    # @schema default: []
    valuesFiles: []
