# A Helm Chart for an IOC instance
apiVersion: v2
name: ioc-instance

# updated by CI when tagging a release
version: 1.0.0

type: application
sources:
  - https://github.com/epics-containers/ec-helm-charts