# examples of objects in values.yaml that default to empty and have no K8S schema
# used for generating schema for these objects
# see .schema.config.yaml

ioc-instance:
  # None required for this Chart.
  # @schema: add
  extraContainers:
    - name: my-sidecar # @schema required
      image: busybox # @schema required
      command: # @schema required
        - sleep
      args: # @schema required
        - "3600" # sleep for an hour

  initContainers:
    - name: my-sidecar # @schema required
      image: busybox # @schema required
      command: # @schema required
        - sleep
      args: # @schema required
        - "3600" # sleep for an hour
